FROM uccser/python:3.6.2-stretch
LABEL maintainer="csse-education-research@canterbury.ac.nz"

# Arguments and Environment Variables
ARG DEBIAN_FRONTEND=noninteractive
ARG PROCESS_PORT=5000
ENV PORT ${PROCESS_PORT}


# Install dependencies
COPY queue/requirements.txt /
RUN /docker_venv/bin/pip3 install -r /requirements.txt

# Setup Working Directory
RUN mkdir /queue
ADD ./queue /queue
WORKDIR /queue

EXPOSE ${PORT}

CMD /docker_venv/bin/gunicorn -c ./gunicorn.conf.py -b :${PORT} wsgi
